welcome = "Guess The Number between 0 and 100 \nChose difficulty: Easy(20)tries, normal(10)tries, Hard(5)tries"
difficulty = "Easy: 1, Normal: 2, Hard:3 \nEnter Difficulty: "
too_low = "Number is lower."
too_high = "Number is higher."
win = f"Congratulations! \nYou guest that the number is"
range_of_numbers = "Chose range (0 - 100): 1, (0 - 1 000): 2\nEnter Range: "
